"""Guard against ORM models silently drifting from the applied migration
history.

Spins up a throwaway Postgres (testcontainers, same image as
tests/integration/conftest.py), applies every migration, then asks Alembic's
own autogenerate comparison whether `Base.metadata` still matches the result.
A model/migration pair that's deliberately out of sync (e.g. a DB-generated
column only ever read via raw SQL) should still be declared in the ORM to
keep this check meaningful.

Run via `make schema-check` (wired into `precommit` only — not `check`,
since it needs Docker; `make check` is meant to stay fast).
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from alembic import command
from alembic.config import Config
from alembic.util import AutogenerateDiffsDetected
from testcontainers.postgres import PostgresContainer  # type: ignore[import-untyped]

from app.config import App, Database, LLM, Redis, Settings


def main() -> int:
    with PostgresContainer("postgres:16-alpine") as pg:
        # Настройки собираются поимённо, а не читаются из .env: проверка обязана
        # ходить в СВОЙ одноразовый контейнер. Подхвати она окружение разработчика
        # — и `alembic upgrade head` уехал бы в рабочую базу.
        settings = Settings(
            app=App(
                env="development",
                api_base_url="http://localhost:8000",
                frontend_base_url="http://localhost:5173",
                fernet_key="dGVzdC1mZXJuZXQta2V5LTMyLWJ5dGVzLWxvbmchISE=",
            ),
            database=Database(
                host=pg.get_container_host_ip(),
                port=int(pg.get_exposed_port(5432)),
                user=pg.username,
                password=pg.password,
                name=pg.dbname,
            ),
            redis=Redis(),
            llm=LLM(),
        )
        os.environ["ALEMBIC_DB_URL"] = settings.database.url
        cfg = Config("alembic.ini")
        command.upgrade(cfg, "head")
        try:
            command.check(cfg)
        except AutogenerateDiffsDetected as e:
            print("Schema drift detected — ORM models don't match the migrated schema:")
            print(f"  {e}")
            print(
                "\nEvery table/column/index/FK the migrations create must be "
                "declared in the matching app/infrastructure/db/models/*.py file "
                "(or, for a deliberate omission — e.g. a DB-generated column only "
                "ever read via raw SQL — leave a comment explaining why)."
            )
            return 1
    print("Schema check: ORM models match the migrated schema. OK.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
